train_path: /content/Creatures/Train
valid_path: /content/Creatures/Valid
test_path: /content/Creatures/Valid
save_path: /content/save/
type_model: "CNN"
patience: 5
image_C: 3
image_W: 224
image_H: 224
num_classes: 15
batch_size: 128
learning_rate: 0.001
num_epochs: 100
