train_path: /content/DS103/data/intermediate/train1.pkl
test_path: /content/Creatures/Valid
save_path: /content/save/
type_model: nn
n_hidden: 50
patience: 5
n_out: 1
batch_size: 256
learning_rate: 0.001
num_epochs: 100
